runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT travel.wsgi:application

handlers:
- url: /static
  static_dir: booking/static/

- url: /.*
  script: auto

runtime_config:
  python_version: 3
  