# Generated by Django 3.1.1 on 2020-10-28 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('itinerary', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.ManyToManyField(blank=True, related_name='listings', to='booking.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='booking.destination')),
            ],
        ),
    ]
