# Generated by Django 3.1.1 on 2020-10-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_listing_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_date']},
        ),
    ]
