# Generated by Django 3.1.1 on 2020-11-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_listing_pick_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
