# Generated by Django 3.1.1 on 2020-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_listing_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
