# Generated by Django 3.1.1 on 2020-11-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_orderitem_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='trip_date',
            new_name='reservation_date',
        ),
    ]
