# Generated by Django 3.1.1 on 2020-12-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20201225_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
